### PR TITLE
Use zarr default compressor by default

### LINKED ISSUE #250: write_multiscale defaults to no compression
Is this intentional?

I'm on main/master.

```python
import numpy as np
import dask.array as da
import zarr
from ome_zarr.io import parse_url
from ome_zarr.writer import write_multiscale
from pathlib import Path
from tempfile import TemporaryDirectory

with TemporaryDirectory(suffix='.ome.zarr') as path:
    arr = da.zeros(  # 100MB array, 4MB chunks, trivially compressible
            (25, 50, 200, 400), dtype=np.uint8, chunks=(1, 50, 200, 400)
            )
    store = parse_url(path, mode='w').store
    root = zarr.group(store=store)
    write_multiscale([arr], group=root, axes='tzyx')

    # chunk size on disk in MB
    print((Path(path) / '0/0/0/0/0').stat().st_size / 1e6)
```

Prints: 4.0

Bonus points if anyone can answer my Q on [Twitter](https://twitter.com/jnuneziglesias/status/1627434802461954048) or [Mastodon](https://fosstodon.org/@jni/109893759738828229)! 😂

### PR DESCRIPTION
**Pull request by jni**
Fixes #250 

Notes:
- I couldn't get pre-commit to work on my machine — some Poetry error? — so apologies if there's some formatting issues, will fix
- The tests will fail if zarr ever changes its defaults to no compression, but that seems like a small risk.

### CODE REVIEW

**Comment by jni** [comment]
> I couldn't get pre-commit to work on my machine

Oh good! It's not just me 😅

**Comment by jni** [comment]
@will-moore rebasing fixed the CI! Let me know if this works for you guys or if you'd prefer a different fix!

**Review by will-moore — APPROVED** [review]
Looks great - thanks.
cc @joshmoore @sbesson

**Comment by jni** [comment]
Oh, all right! No worries, just let me know. 😊

**Pull request merged**
