### PR TITLE
Support init of ome_zarr_py.io.ZarrLocation with zarr.storage.FSStore

### PR DESCRIPTION
**Pull request by berombau**
By supporting FSStore as input, more complex ZarrLocations are possible like private remote stores.

### CODE REVIEW

**Comment by berombau** [comment]
@joshmoore Sure, I added some basic tests. More bespoke testing would require a dependency on s3fs or universal_pathlib, but this covers my use case.

**Comment by berombau** [comment]
It's ready to go in the next release, I think. I worked with `universal-pathlib` and `moto` in a spatialdata fork and it works well, but it's better to work on that if needed in a separate PR.

**Comment by joshmoore** [comment]
Thanks, all! Due to the change of the API, going to release this now as 0.9.0. @pgarrison, interested to hear if it solves all your troubles. 🙂

**Comment by pgarrison** [comment]
@joshmoore yes I was [able to use this pattern](https://github.com/bioio-devs/bioio-ome-zarr/pull/25) to read a public `s3://` path without authentication, thanks all!

**Pull request merged**
