### PR TITLE
Add linter.yml

### PR DESCRIPTION
**Pull request by joshmoore**
see: https://github.com/github/super-linter

### CODE REVIEW

**Comment by joshmoore** [comment]
Need to find a way to add requirements into the linter docker.

**Comment by manics** [comment]
Could add a pre-commit config for black and flake8 instead? There's an upstream action https://github.com/pre-commit/action

**Comment by joshmoore** [comment]
Certainly no objection. Give it a try. You'd have it run on every push to the branch or only on merge? I'm not exactly sure how the synchronization with upstream is going to work in the latter case.

**Comment by joshmoore** [comment]
> Could add a pre-commit config for black and flake8 instead?

I missed the "instead". Still no objections, but part of my goal was to have something that would lint more than just Python that we could use across all repos _a la_ https://docs.github.com/en/actions/configuring-and-managing-workflows/sharing-workflow-templates-within-your-organization

**Pull request closed without merging**
