### PR TITLE
Add all ome_zarr modules to the generated API documentation

### PR DESCRIPTION
**Pull request by sbesson**
Builds on top of #121 and exposes all the modules as single pages

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ome-zarr--181.org.readthedocs.build/en/181/api.html for the documentation built from this PR

**Comment by will-moore** [comment]
Looks good!
The `@param` are not formatted correctly at https://ome-zarr--181.org.readthedocs.build/en/181/api/csv.html#ome_zarr.csv.csv_to_zarr

**Comment by sbesson** [comment]
:+1: updated all remaining usages of `@param` to `:param` - see https://ome-zarr--181.org.readthedocs.build/en/181/api/csv.html. The writer API uses a standard dictionary style for the parameters and could also use this markup but I would propose not to update these before #178 is merged as new methods are introduced

**Comment by will-moore** [comment]
Thanks. The `writer API` style looks good too, and formats well with the longer param descriptions, so hopefully it'll work OK with `:param` too.

**Review by will-moore — APPROVED** [review]
LGTM 👍

**Pull request merged**
