### PR TITLE
better error handling

### PR DESCRIPTION
**Pull request by joshmoore**
Thanks to @tlambert03 and https://github.com/napari/napari/pull/1219, starting the plugin with a bad URL showed much more information about what went wrong. With this PR, we catch the exception and log it at `WARNING` which is _not_ shown to the user by default:

```
(py36) /opt/ome-zarr-py $napari http://localhost:8080/idr/zarr/v0.1/151.zarr
11:32:27 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('Not a zarr dataset or group: http://localhost:8080/idr/zarr/v0.1/151.zarr',)
    in file: /opt/anaconda/envs/py36/lib/python3.6/site-packages/napari/utils/io.py
    at line: 272
    package: napari
    version: 0.3.1

11:32:27 WARNING No plugin found capable of reading 'http://localhost:8080/idr/zarr/v0.1/151.zarr'.
11:32:27 ERROR (1) error occured in plugins: 'builtins'. See full error logs in "Plugins → Plugin Errors..."
```

### CODE REVIEW

**Comment by tlambert03** [comment]
Glad that came in handy!  Just in case you missed it, another recently merged feature that you might find useful is the ability to pass a plugin like `--plugin ome-zarr` on the CLI: https://github.com/napari/napari/pull/1220

(Still no plugin params though)

**Comment by joshmoore** [comment]
@mtbc @will-moore : I've add on some more fault-handling code here since this PR has the logging in place (probably best to get it merged sooner rather than later).

I could use some feedback on https://github.com/ome/ome-zarr-py/pull/22/commits/c20db1758bc64f6382d94010590cb79033a6c89e:

 - should omero-ms-zarr be passing back `label` at all cost?
 - are there default values we can specify for start/end that would be more robust?
 - what values can safely be missing from the metadata that's passed to napari?

**Comment by mtbc** [comment]
All good questions! For each key it could be good to specify from where in OMERO to get the value and, if missing and required, what to invent and how.

**Comment by jburel** [comment]
If you fail to retrieve the rendering settings, you could also fall back to the pixels type to set the range but that will mean implementing some logic to set the start/end interval

**Comment by will-moore** [comment]
I think all of the metadata can be omitted and napari will happily use defaults. The only exception is probably window start/end which are used for contrast setting.
If we don't set these then napari may try to load a ton of data to try and establish min/max.
As @jburel says, we could try to return min/max based on pixel type (since we have some data in hand, but as we were discussing for OMERO, the full range can give a poor experience with rendering sliders. We could potentially get a sample plane (mid Z/T index) and use that to estimate range (e.g. min = 0 and max = plane.max * 2), which could give a more useful range that pixelType max.
But choosing the plane is maybe a bit trickier with multi-resolution images (unless we use the lowest resolution which might be a single tile). I think napari loads that anyway to use for the channel thumbnail.

**Comment by joshmoore** [comment]
@will-moore : :+1: are there any concrete changes you would make to this patch? (Would also be good to eventually encapsulate that in the spec.md as @mtbc suggests)

**Comment by will-moore** [comment]
I don't know if we want to check that the ```len(channels)``` is correct (same length as the C-dimension of the pixel data), or just assume it is?
If it's not, napari fails as above.

**Comment by joshmoore** [comment]
That all makes sense and I'll update, but I think I was more concerned about what happens if an internal element is missing. (In this case, a missing `label` key was throwing an exception.)

**Comment by will-moore** [comment]
OK, understood.
It seems from my test above that napari is not grabbing all the remote data to choose contrast limits. So you can probably leave ```metadata['contrast_limits']``` unset if you don't have a 'end' value for every channel? Probably safer than passing an incomplete list.

**Comment by joshmoore** [comment]
Ok. Added those checks. Have a look at the last two commits.

**Comment by jburel** [comment]
test failed

**Comment by will-moore** [comment]
Code changes look good, thanks

**Comment by will-moore** [comment]
👍

**Pull request merged**
