### PR TITLE
Update version of pyupgrade

### PR DESCRIPTION
**Pull request by dstansby**
This updates the version of pyupgrade to match the minimum supported version of the package, and makes the corresponding pyupgrade fixes.

### CODE REVIEW

**Comment by joshmoore** [comment]
@dstansby: can you handle the conflicts here?

**Comment by dstansby** [comment]
👍 should be updated and fixed now

**Review by joshmoore — APPROVED** [review]
MSTM. @will-moore, any concerns about getting this in now?

**Comment by will-moore** [comment]
LGTM 👍

**Pull request merged**
