### PR TITLE
Cap aiohttp to 3.x versions

### PR DESCRIPTION
**Pull request by sbesson**
Versions 4.0.0a1 recently released includes breaking changes which break the tests e.g. https://github.com/ome/ome-zarr-py/actions/runs/1435189763 

```
------------------------------ Captured log call ------------------------------
WARNING  ome_zarr.io:io.py:190 exception on parsing: __init__() got an unexpected keyword argument 'loop' (stacktrace at DEBUG)
ERROR    ome_zarr.cli:cli.py:168 not a zarr: None
============================== warnings summary ===============================
tests/test_cli.py::TestCli::test_s3_info[v0.1]
tests/test_cli.py::TestCli::test_s3_info[v0.2]
tests/test_cli.py::TestCli::test_s3_info[v0.3]
  D:\a\ome-zarr-py\ome-zarr-py\.tox\py39\lib\site-packages\_pytest\unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function ClientSession.__del__ at 0x0000027B4B773DC0>
  
  Traceback (most recent call last):
    File "D:\a\ome-zarr-py\ome-zarr-py\.tox\py39\lib\site-packages\aiohttp\client.py", line 269, in __del__
      if not self.closed:
    File "D:\a\ome-zarr-py\ome-zarr-py\.tox\py39\lib\site-packages\aiohttp\client.py", line 894, in closed
      return self._connector is None or self._connector.closed
  AttributeError: _connector
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

### CODE REVIEW

**Comment by joshmoore** [comment]
No objections as a temporary fix, but we may need to push upstream. Do you know what version of fsspec was being used in the failed build?

**Comment by sbesson** [comment]
> No objections as a temporary fix, but we may need to push upstream

You mean in `aiohttp` itself (I assume the breaking changes are expected given the major version increment) or in the library consuming `aiohttp` (assuming `fsspec`)?

**Comment by joshmoore** [comment]
The latter. Something like: https://github.com/fsspec/s3fs/issues/513

**Comment by sbesson** [comment]
Now reported upstream as https://github.com/fsspec/filesystem_spec/issues/819 and added a reference in `setup.py` via afe173c.

**Comment by joshmoore** [comment]
I've pinged on your issue.

**Comment by joshmoore** [comment]
Ran into these failures again. Haven't seen any movement upstream so merging and opening an issue to review.

**Pull request merged**
