### PR TITLE
Register napari conftest

### PR DESCRIPTION
**Pull request by Czaki**
@joshmoore I test this locally and (with removed skip) all tests passed. 
May you think to change this if to detect if the test is run on CI? 

There is `GITHUB_ACTIONS` in the environment.

```
GITHUB_ACTIONS = "GITHUB_ACTIONS" in os.environ
```

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @Czaki. Certainly looking better in #51.

> May you think to change this if to detect if the test is run on CI?

You're saying that you would disable Qt tests on CI completely?

**Comment by Czaki** [comment]
> You're saying that you would disable Qt tests on CI completely?

No. If the problem with test is only on CI (because of GL drive or no screen), then test should be disabled only on CI.

**Comment by joshmoore** [comment]
Of course! I had hoped the fix would be quick and we could remove that but unfortunately that hasn't been the case.

**Comment by Czaki** [comment]
> Of course! I had hoped the fix would be quick and we could remove that but unfortunately that hasn't been the case.

In my program, I disable part of tests that use napari viewer because of problems on CI, where I do not have time to investigate what wrong is with the configuration of environments. MacOS cover all tests.

**Comment by joshmoore** [comment]
Understood. That may be the next step if I can't get it working this morning. Another option I've been considering is to extract the napari plugin out of ome-zarr-py (e.g. `napari-ome-zarr`).

**Comment by joshmoore** [comment]
Closing now. Thanks again!

**Pull request closed without merging**
