### PR TITLE
Deactivate Zarr dev build

### PR DESCRIPTION
**Pull request by joshmoore**
This build was put in place by the Zarr team in order to check for potential issues in downstream projects after PRs have been merged. For some reason, it is now aborting with little to no logging. In https://github.com/zarr-developers/zarr-python/issues/1328 the `texasbbq` package from Numba has been suggested for a similar purpose. This workflow might could be rewritten using such a tool.

### CODE REVIEW

**Comment by joshmoore** [comment]
Now linting is failing!

**Comment by will-moore** [comment]
```
RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```
I *think* that was what I was fixing with https://github.com/ome/ome-zarr-py/pull/244/commits/737228a01fecd441129924fcf4a30db71a37c885 but I don't see the record of it in that PR now, possible due to force pushing at one point

**Comment by will-moore** [comment]
All green except test coverage!

**Review by will-moore — APPROVED** [review]
According to https://github.com/codecov/codecov-action/issues/598 the test-coverage fail is a flaky issue. Re-running got it green this time!
Good to merge

**Pull request merged**
