### PR TITLE
Add aiohttp as a requirement

### PR DESCRIPTION
**Pull request by joshmoore**
In preparing a conda example for #40, a run-time exception was thrown during `ome_zarr info ...`. Installing aiohttp solved the problem.

<details>
<summary>aiohttp error on fresh Python 3.8 conda</summary>

```
(base) ~ $conda create -n example -c conda-forge zarr
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/anaconda3/envs/example

  added / updated specs:
    - zarr


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.8.0              |      17_openblas          11 KB  conda-forge
    libcblas-3.8.0             |      17_openblas          11 KB  conda-forge
    libcxx-10.0.1              |       h5f48129_0         1.0 MB  conda-forge
    liblapack-3.8.0            |      17_openblas          11 KB  conda-forge
    libopenblas-0.3.10         |openmp_h63d9170_4         8.2 MB  conda-forge
    llvm-openmp-10.0.1         |       h28b9765_0         265 KB  conda-forge
    ncurses-6.2                |       hb1e8313_1         902 KB  conda-forge
    numpy-1.19.1               |   py38h598c1e0_0         5.1 MB  conda-forge
    openssl-1.1.1g             |       h0b31af3_1         1.9 MB  conda-forge
    pip-20.2.1                 |             py_0         1.1 MB  conda-forge
    python-3.8.5               |h85f3143_2_cpython        31.8 MB  conda-forge
    readline-8.0               |       h0678c8f_2         255 KB  conda-forge
    setuptools-49.3.1          |   py38h32f6830_0         919 KB  conda-forge
    sqlite-3.32.3              |       h93121df_1         1.7 MB  conda-forge
    xz-5.2.5                   |       h0b31af3_1         227 KB  conda-forge
    zlib-1.2.11                |             1007         102 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        53.5 MB

The following NEW packages will be INSTALLED:

  asciitree          conda-forge/noarch::asciitree-0.3.3-py_2
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.6.20-hecda079_0
  certifi            conda-forge/osx-64::certifi-2020.6.20-py38h32f6830_0
  fasteners          conda-forge/noarch::fasteners-0.14.1-py_3
  libblas            conda-forge/osx-64::libblas-3.8.0-17_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-17_openblas
  libcxx             conda-forge/osx-64::libcxx-10.0.1-h5f48129_0
  libffi             conda-forge/osx-64::libffi-3.2.1-h4a8c4bd_1007
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  liblapack          conda-forge/osx-64::liblapack-3.8.0-17_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.10-openmp_h63d9170_4
  llvm-openmp        conda-forge/osx-64::llvm-openmp-10.0.1-h28b9765_0
  monotonic          conda-forge/noarch::monotonic-1.5-py_0
  msgpack-python     conda-forge/osx-64::msgpack-python-1.0.0-py38ha0d09dd_1
  ncurses            conda-forge/osx-64::ncurses-6.2-hb1e8313_1
  numcodecs          conda-forge/osx-64::numcodecs-0.6.4-py38h4a8c4bd_0
  numpy              conda-forge/osx-64::numpy-1.19.1-py38h598c1e0_0
  openssl            conda-forge/osx-64::openssl-1.1.1g-h0b31af3_1
  pip                conda-forge/noarch::pip-20.2.1-py_0
  python             conda-forge/osx-64::python-3.8.5-h85f3143_2_cpython
  python_abi         conda-forge/osx-64::python_abi-3.8-1_cp38
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  setuptools         conda-forge/osx-64::setuptools-49.3.1-py38h32f6830_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/osx-64::sqlite-3.32.3-h93121df_1
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/osx-64::xz-5.2.5-h0b31af3_1
  zarr               conda-forge/noarch::zarr-2.4.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-1007


Proceed ([y]/n)? y


Downloading and Extracting Packages
openssl-1.1.1g       | 1.9 MB    | ########################################### | 100%
xz-5.2.5             | 227 KB    | ########################################### | 100%
libopenblas-0.3.10   | 8.2 MB    | ########################################### | 100%
pip-20.2.1           | 1.1 MB    | ############################################################################################ | 100%
numpy-1.19.1         | 5.1 MB    | ############################################################################################ | 100%
llvm-openmp-10.0.1   | 265 KB    | ############################################################################################ | 100%
ncurses-6.2          | 902 KB    | ############################################################################################ | 100%
libblas-3.8.0        | 11 KB     | ############################################################################################ | 100%
zlib-1.2.11          | 102 KB    | ############################################################################################ | 100%
liblapack-3.8.0      | 11 KB     | ############################################################################################ | 100%
readline-8.0         | 255 KB    | ############################################################################################ | 100%
python-3.8.5         | 31.8 MB   | ############################################################################################ | 100%
libcblas-3.8.0       | 11 KB     | ############################################################################################ | 100%
setuptools-49.3.1    | 919 KB    | ############################################################################################ | 100%
libcxx-10.0.1        | 1.0 MB    | ############################################################################################ | 100%
sqlite-3.32.3        | 1.7 MB    | ############################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate example
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ~ $conda activate example
(example) ~ $pip install ome-zarr
Collecting ome-zarr
  Using cached ome_zarr-0.0.10-py3-none-any.whl (8.4 kB)
Collecting dask
  Downloading dask-2.22.0-py3-none-any.whl (828 kB)
     |████████████████████████████████| 828 kB 1.0 MB/s
Requirement already satisfied: numpy in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from ome-zarr) (1.19.1)
Collecting s3fs
  Using cached s3fs-0.4.2-py3-none-any.whl (19 kB)
Processing ./Library/Caches/pip/wheels/a5/2b/b5/05758d5828d65f2adef8fbb5d5484e4adb946ae1827a973a01/toolz-0.10.0-py3-none-any.whl
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Processing ./Library/Caches/pip/wheels/60/f9/ba/c802b3bb175c9f158667b47f71be5aab048f25cb5c46c69646/vispy-0.6.4-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: zarr in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from ome-zarr) (2.4.0)
Processing ./Library/Caches/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting fsspec>=0.6.0
  Downloading fsspec-0.8.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 792 kB/s
Collecting botocore>=1.12.91
  Downloading botocore-1.17.39-py2.py3-none-any.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 594 kB/s
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from requests->ome-zarr) (2020.6.20)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting freetype-py
  Using cached freetype_py-2.2.0-py3-none-macosx_10_9_x86_64.whl (852 kB)
Requirement already satisfied: fasteners in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from zarr->ome-zarr) (0.14.1)
Requirement already satisfied: asciitree in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from zarr->ome-zarr) (0.3.3)
Requirement already satisfied: numcodecs>=0.6.4 in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from zarr->ome-zarr) (0.6.4)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: six in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from fasteners->zarr->ome-zarr) (1.15.0)
Requirement already satisfied: monotonic>=0.1 in /usr/local/anaconda3/envs/example/lib/python3.8/site-packages (from fasteners->zarr->ome-zarr) (1.5)
Installing collected packages: pyyaml, dask, fsspec, urllib3, docutils, jmespath, python-dateutil, botocore, s3fs, toolz, idna, chardet, requests, freetype-py, vispy, ome-zarr
Successfully installed botocore-1.17.39 chardet-3.0.4 dask-2.22.0 docutils-0.15.2 freetype-py-2.2.0 fsspec-0.8.0 idna-2.10 jmespath-0.10.0 ome-zarr-0.0.10 python-dateutil-2.8.1 pyyaml-5.3.1 requests-2.24.0 s3fs-0.4.2 toolz-0.10.0 urllib3-1.25.10 vispy-0.6.4
(example) ~ $ome_zarr info https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr
conda deactivateroot_attrs {'multiscales': [{'datasets': [{'path': '0'}, {'path': '1'}], 'version': '0.1'}], 'omero': {'channels': [{'active': True, 'coefficient': 1.0, 'color': '0000FF', 'family': 'linear', 'inverted': False, 'label': 'LaminB1', 'window': {'end': 1500.0, 'max': 65535.0, 'min': 0.0, 'start': 0.0}}, {'active': True, 'coefficient': 1.0, 'color': 'FFFF00', 'family': 'linear', 'inverted': False, 'label': 'Dapi', 'window': {'end': 1500.0, 'max': 65535.0, 'min': 0.0, 'start': 0.0}}], 'id': 6001240, 'name': 'B1_C1.tif', 'rdefs': {'defaultT': 0, 'defaultZ': 118, 'model': 'color'}, 'version': '0.1'}}
resolutions ['0', '1']
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/registry.py", line 186, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/registry.py", line 201, in _import_class
    mod = importlib.import_module(mod)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/implementations/http.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/example/bin/ome_zarr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/ome_zarr_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/ome_zarr_cli.py", line 11, in info
    zarr_info(args.path)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/ome_zarr.py", line 307, in info
    data = reader(path)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/ome_zarr.py", line 139, in reader_function
    layers = [self.load_ome_zarr()]
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/ome_zarr.py", line 237, in load_ome_zarr
    data = da.from_zarr(f"{self.zarr_path}{resolution}")
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/dask/array/core.py", line 2878, in from_zarr
    mapper = get_mapper(url, **storage_options)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/mapping.py", line 183, in get_mapper
    fs, urlpath = url_to_fs(url, **kwargs)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/core.py", line 337, in url_to_fs
    fs = filesystem(protocol, **kwargs)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/registry.py", line 218, in filesystem
    cls = get_filesystem_class(protocol)
  File "/usr/local/anaconda3/envs/example/lib/python3.8/site-packages/fsspec/registry.py", line 188, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: HTTPFileSystem requires "requests" to be installed
```

</details>

Suggest for immediate patch release if older versions also pass.

### CODE REVIEW

**Comment by jburel** [comment]
should 3.8 be added to testing matrix in travis file in that case?
it is pinned at 3.6

**Comment by jburel** [comment]
is the dependency fetched by another dependency when using Python < 3.8?

**Comment by joshmoore** [comment]
I don't know. It could happen for earlier Python versions as well. I assume it's a change in upstream somewhere and only shows up at runtime.

**Comment by jburel** [comment]
change looks good. Travis now tests 3.6, 3.7, 3.8
Good to merge

**Pull request merged**
