### PR TITLE
Cleanup builds

### PR DESCRIPTION
**Pull request by joshmoore**
After the extraction of the napari plugin to `napari-ome-zarr`,
a number of the matrix builds can be eliminated. This PR attempts
to drop any dependencies on Qt-related code which should all be in
the plugin repository.

### CODE REVIEW

**Comment by joshmoore** [comment]
@will-moore : in order to get rid of the vispy dependency, can you see just adding these values raw rather than wrapping them with a `Colormap`?

```
                color = ch.get("color", None)
                if color is not None:
                    rgb = [(int(color[i : i + 2], 16) / 255) for i in range(0, 6, 2)]
                    # TODO: make this value an enumeration
                    if model == "greyscale":
                        rgb = [1, 1, 1]
                    colormaps.append(Colormap([[0, 0, 0], rgb]))
```

**Comment by will-moore** [comment]
A `Colormap` was added here because that's what `napari` was expecting.

It looks like `napari` is still expecting a [napari colormap](https://napari.org/docs/0.4.7/_modules/napari/utils/colormaps/colormap.html#Colormap) in `add_image`: https://napari.org/docs/0.4.7/api/napari.Viewer.html#napari.Viewer.add_image but this won't be needed
now that napari support is moved to napari-ome-zarr.

**Comment by joshmoore** [comment]
So store `[[0, 0, 0], rgb]` and then transform in napari-ome-zarr? Or introduce an object here?

**Comment by will-moore** [comment]
I would think that `[[0, 0, 0], rgb]` would be fine, but happy to use an Object if it's clearer etc.

**Comment by joshmoore** [comment]
Failure is caused by the recently merged https://github.com/zarr-developers/zarr-python/pull/781

**Review by constantinpape — APPROVED** [review]
@joshmoore this looks good. Could we merge this now and then merge main into #89 in order to simplify the tests?

**Comment by joshmoore** [comment]
Yeah, let's do that. Then we can build up our confidence in this a bit more in this PR before cutting a release.

**Pull request merged**
