### PR TITLE
Fix scalar chunking

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/ome/ome-zarr-py/issues/364. I noticed there wasn't a changelog, so I added one, I hope that's okay? I think it's important to communicate bug fixes like this.

### CODE REVIEW

**Comment by will-moore** [comment]
Thanks for the contribution and the changelog.
Could you add a link from the changelog to this issue? In other repos do this (e.g. https://github.com/ome/omero-web/blob/master/CHANGELOG.md) which also allows you to be more concise in the changelog if you wish?

The change looks good and makes sense. The only question I have is whether anyone would consider this a breaking API change (and therefore require a major version bump) or if this is really just a bug fix? cc @joshmoore

**Review by will-moore — APPROVED** [review]
Thanks for the update. LGTM.

Previously, doing `write_image(....storage_options={"chunks": 32})` would have resulted in chunks of e.g `(sizeZ, sizeY, 32)` but this feature wasn't documented or have tests and the behaviour was different from zarr-python.
So, I think we could consider a change in this behaviour to be a bug-fix rather than a breaking API change, but happy to hear other opinions @joshmoore @sbesson ?

**Review by joshmoore — CHANGES_REQUESTED** [review]
Please see https://github.com/ome/ome-zarr-py/blob/master/CHANGELOG.md

**Comment by dstansby** [comment]
👍 changelog in the right place now - I think tests are failing because codecov now requires a token to upload coverage reports.

**Pull request merged**
